'use strict';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random()),clone=x=>JSON.parse(JSON.stringify(x)),store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const templates={score:{name:'Score Tracker',icon:'🔢',type:'score',label:'Questions correct',max:20},dual:{name:'Weekly Round-Up',icon:'🔤',type:'dual',left:'Spellings',right:'Tables',leftMax:10,rightMax:10},text:{name:'Certificate Tracker',icon:'🏆',type:'text',label:'Certificate name'},guided:{name:'Guided Reading',icon:'📖',type:'guided',criteria:['Fluency','Diction','Volume','Expression','Comprehension']},wellbeing:{name:'Wellbeing Check-In',icon:'💚',type:'wellbeing'}};
const seed=['Dexter','Jack','Melita','Scarlett','Jayden','Ani','Katie'];
function builtIns(){return[{id:'guided',...clone(templates.guided),enabled:true,builtIn:true,groups:[{name:'Whole class',book:'',pupils:[...seed]}]},{id:'weekly',...clone(templates.dual),enabled:true,builtIn:true,groups:[{name:'Whole class',leftMax:10,rightMax:10,pupils:[...seed]}]},{id:'mental',...clone(templates.score),name:'Mental Maths',enabled:true,builtIn:true,groups:[{name:'Whole class',max:20,pupils:[...seed]}]},{id:'certificate',...clone(templates.text),enabled:true,builtIn:true},{id:'intervention',...clone(templates.text),name:'Intervention Tracker',label:'Intervention name',icon:'🧩',enabled:true,builtIn:true}]}
let classes=read('sb9_classes',[{id:uid(),name:'P7SC',pupils:[...seed],tools:builtIns()}]),records=read('sb9_records',[]),ci=0,tool=null,pupil='',draft=null,portalFilter='All',editId='';
function migrateData(){classes.forEach(c=>{c.pupils=Array.isArray(c.pupils)?c.pupils:[];c.tools=Array.isArray(c.tools)?c.tools:builtIns();for(const built of builtIns()){if(!c.tools.some(t=>t.id===built.id))c.tools.push(built)}c.tools.forEach(t=>{t.enabled=t.enabled!==false;if(['score','dual'].includes(t.type)&&!Array.isArray(t.groups))t.groups=[{name:'Whole class',max:t.max||10,leftMax:t.leftMax||10,rightMax:t.rightMax||10,pupils:[...c.pupils]}];if(t.type==='guided'&&!Array.isArray(t.groups))t.groups=[{name:'Whole class',book:'',pupils:[...c.pupils]}]})});store('sb9_classes',classes)}

const cls=()=>classes[ci],find=id=>cls().tools.find(t=>t.id===id),day=(d=new Date())=>d.toISOString().slice(0,10),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('hidden',p.id!==id));$('nav').classList.toggle('hidden',id==='login')}
function renderClasses(){$('classTiles').innerHTML=classes.map((c,i)=>`<button class="tile" data-class="${i}">🏫 ${esc(c.name)}</button>`).join('');show('classes')}
function renderTools(){$('classTitle').textContent=cls().name;$('toolTiles').innerHTML=cls().tools.filter(t=>t.enabled).map(t=>`<button class="tile" data-tool="${t.id}">${t.icon} ${esc(t.name)}</button>`).join('');show('tools')}
function completed(n){return records.some(r=>r.classId===cls().id&&r.toolId===tool.id&&r.pupil===n&&day(new Date(r.date))===day())}
function openTool(id){tool=find(id);$('toolTitle').textContent=tool.name;$('pupilTiles').innerHTML=cls().pupils.map(n=>`<button class="pupil" ${completed(n)?'disabled':''} data-pupil="${encodeURIComponent(n)}">${esc(n)}${completed(n)?' ✓':''}</button>`).join('');show('names')}
function openEntry(n){pupil=decodeURIComponent(n);draft={};$('entryTitle').textContent=`${pupil} · ${tool.name}`;let h='';if(tool.type==='score'){let g=(tool.groups||[]).find(g=>g.pupils.includes(pupil))||{max:tool.max};h=`<p>${esc(tool.label)} out of ${g.max}</p><div class="scores">${buttons(g.max,'score')}</div>`}else if(tool.type==='dual'){let g=tool.groups.find(g=>g.pupils.includes(pupil))||tool.groups[0];h=`<div class="dual"><div><h3>${esc(tool.left)} out of ${g.leftMax}</h3><div class="scores">${buttons(g.leftMax,'left')}</div></div><div><h3>${esc(tool.right)} out of ${g.rightMax}</h3><div class="scores">${buttons(g.rightMax,'right')}</div></div></div>`}else if(tool.type==='text'){h=`<label>${esc(tool.label)}<input id="textValue"></label>`}else if(tool.type==='guided'){h=`<label>Book<input id="bookValue"></label>${tool.criteria.map(c=>`<div><b>${esc(c)}</b><div class="scores">${[1,2,3,4,5].map(v=>`<button class="score" data-kind="criterion" data-key="${encodeURIComponent(c)}" data-value="${v}">${v}</button>`).join('')}</div></div>`).join('')}<label>Notes<textarea id="notesValue"></textarea></label>`}else if(tool.type==='wellbeing'){h=`<div class="scores">${[1,2,3,4,5].map(v=>`<button class="score" data-kind="mood" data-value="${v}">${v}</button>`).join('')}</div><label>Feeling<input id="feelingValue"></label><label>Reason<input id="reasonValue"></label><label>Notes<textarea id="notesValue"></textarea></label>`}$('entryBody').innerHTML=h;$('entryModal').classList.remove('hidden')}
function buttons(max,kind){return Array.from({length:Number(max)+1},(_,v)=>`<button type="button" class="score" data-kind="${kind}" data-value="${v}" data-max="${max}">${v}</button>`).join('')}
function saveEntry(){try{let details={};if(tool.type==='score'){if(draft.score==null)throw Error('Select a score');details={Label:tool.label,Score:draft.score,OutOf:draft.max}}else if(tool.type==='dual'){if(draft.left==null||draft.right==null)throw Error('Select both scores');details={LeftLabel:tool.left,Left:draft.left,LeftMax:draft.leftMax,RightLabel:tool.right,Right:draft.right,RightMax:draft.rightMax}}else if(tool.type==='text'){let v=$('textValue').value.trim();if(!v)throw Error('Type an entry');details={Label:tool.label,Entry:v}}else if(tool.type==='guided'){if(tool.criteria.some(c=>draft[c]==null))throw Error('Score every criterion');details={Book:$('bookValue').value.trim(),Notes:$('notesValue').value.trim(),...draft}}else{if(draft.Mood==null)throw Error('Choose a mood');details={Mood:draft.Mood,Feeling:$('feelingValue').value,Reason:$('reasonValue').value,Notes:$('notesValue').value}}records.unshift({id:uid(),date:new Date().toISOString(),classId:cls().id,className:cls().name,toolId:tool.id,toolName:tool.name,pupil,details});store('sb9_records',records);$('entryModal').classList.add('hidden');openTool(tool.id)}catch(e){alert(e.message)}}
function openTemplatePicker(){$('templateTiles').innerHTML=Object.entries(templates).map(([k,t])=>`<button class="tile" data-template="${k}">${t.icon} Copy ${esc(t.name)}</button>`).join('');$('templateModal').classList.remove('hidden')}
function createTool(k){let t={id:uid(),...clone(templates[k]),name:`My ${templates[k].name}`,enabled:true,builtIn:false};if(['score','dual'].includes(t.type))t.groups=[{name:'Whole class',max:t.max||10,leftMax:t.leftMax||10,rightMax:t.rightMax||10,pupils:[...cls().pupils]}];if(t.type==='guided')t.groups=[{name:'Whole class',book:'',pupils:[...cls().pupils]}];cls().tools.push(t);store('sb9_classes',classes);$('templateModal').classList.add('hidden');renderManage()}
function renderManage(){$('manageClass').innerHTML=classes.map((c,i)=>`<option value="${i}" ${i===ci?'selected':''}>${esc(c.name)}</option>`).join('');$('className').value=cls().name;$('classList').value=cls().pupils.join('\n');$('manageTools').innerHTML=cls().tools.map(t=>`<div class="card"><b>${t.icon} ${esc(t.name)}</b><label><input type="checkbox" data-enable="${t.id}" ${t.enabled?'checked':''}> Show</label><button data-edit="${t.id}">Edit</button></div>`).join('');show('manage')}
function saveClass(){cls().name=$('className').value.trim()||cls().name;cls().pupils=[...new Set($('classList').value.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean))];document.querySelectorAll('[data-enable]').forEach(x=>find(x.dataset.enable).enabled=x.checked);store('sb9_classes',classes);$('savedMessage').classList.remove('hidden');setTimeout(()=>$('savedMessage').classList.add('hidden'),2000)}
function openPortal(){$('portalClass').innerHTML=classes.map((c,i)=>`<option value="${i}" ${i===ci?'selected':''}>${esc(c.name)}</option>`).join('');let ds=[...new Set(records.filter(r=>r.classId===cls().id).map(r=>day(new Date(r.date))))].sort().reverse();$('portalDay').innerHTML=(ds.length?ds:[day()]).map(d=>`<option>${d}</option>`).join('');renderPortal();show('portal')}
function renderPortal(){let all=records.filter(r=>r.classId===cls().id&&day(new Date(r.date))===$('portalDay').value),shown=portalFilter==='All'?all:all.filter(r=>r.toolName===portalFilter);$('portalTabs').innerHTML=['All',...cls().tools.map(t=>t.name)].map(n=>`<button class="tab ${n===portalFilter?'active':''}" data-tab="${encodeURIComponent(n)}">${esc(n)}</button>`).join('');$('summary').innerHTML=cls().tools.map(t=>`<div class="card"><b>${esc(t.name)}</b><h2>${all.filter(r=>r.toolId===t.id).length}</h2></div>`).join('');$('records').innerHTML=shown.map(r=>`<tr><td>${esc(r.pupil)}</td><td>${esc(r.toolName)}</td><td>${esc(Object.entries(r.details).map(([k,v])=>`${k}: ${v}`).join(' | '))}</td></tr>`).join('')||'<tr><td colspan="3">No records</td></tr>'}
function exportOptions(){$('exportWidgets').innerHTML=cls().tools.map(t=>`<label class="export-item"><input type="checkbox" data-export="${t.id}" checked> ${esc(t.name)}</label>`).join('');$('exportModal').classList.remove('hidden')}
function download(){let ids=[...document.querySelectorAll('[data-export]:checked')].map(x=>x.dataset.export),range=$('exportRange').value,end=new Date(),start=null;if(range==='day'){start=new Date($('portalDay').value+'T00:00:00');end=new Date($('portalDay').value+'T23:59:59')}else if(range!=='all'){start=new Date();if(range==='week')start.setDate(start.getDate()-6);if(range==='month')start.setMonth(start.getMonth()-1);if(range==='three')start.setMonth(start.getMonth()-3);if(range==='year')start.setFullYear(start.getFullYear()-1)}let rr=records.filter(r=>r.classId===cls().id&&ids.includes(r.toolId)&&(!start||new Date(r.date)>=start&&new Date(r.date)<=end)),rows=[['Date','Class','Pupil','Tool','Details'],...rr.map(r=>[r.date,r.className,r.pupil,r.toolName,Object.entries(r.details).map(([k,v])=>`${k}: ${v}`).join(' | ')])],csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='stat-buddy.csv';a.click();$('exportModal').classList.add('hidden')}
document.addEventListener('click',e=>{let pg=e.target.closest('[data-page]');if(pg){pg.dataset.page==='classes'?renderClasses():pg.dataset.page==='manage'?renderManage():renderTools()}let cl=e.target.closest('[data-class]');if(cl){ci=+cl.dataset.class;renderTools()}let t=e.target.closest('[data-tool]');if(t){tool=find(t.dataset.tool);openTool(tool.id)}let p=e.target.closest('[data-pupil]');if(p)openEntry(p.dataset.pupil);let s=e.target.closest('[data-kind]');if(s){s.parentElement.querySelectorAll('.score').forEach(x=>x.classList.toggle('active',x===s));let k=s.dataset.kind,v=+s.dataset.value;if(k==='score'){draft.score=v;draft.max=Number(s.dataset.max)||Number(tool.max)||10}else if(k==='left'){draft.left=v;draft.leftMax=Number(s.dataset.max)||Number(tool.leftMax)||10}else if(k==='right'){draft.right=v;draft.rightMax=Number(s.dataset.max)||Number(tool.rightMax)||10}else if(k==='mood')draft.Mood=v;else draft[decodeURIComponent(s.dataset.key)]=v}let temp=e.target.closest('[data-template]');if(temp)createTool(temp.dataset.template);let tab=e.target.closest('[data-tab]');if(tab){portalFilter=decodeURIComponent(tab.dataset.tab);renderPortal()}if(e.target.closest('.close'))e.target.closest('.modal').classList.add('hidden')});
function bindApp(){
  migrateData();
  $('loginBtn').addEventListener('click',()=>{if($('username').value==='teacher'&&$('password').value==='demo123'){sessionStorage.sb9='1';renderClasses()}else $('loginError').textContent='Incorrect login'});
  $('logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem('sb9');show('login')});
  $('portalBtn').addEventListener('click',openPortal);
  $('createToolBtn').addEventListener('click',openTemplatePicker);
  $('saveEntryBtn').addEventListener('click',saveEntry);
  $('saveClassBtn').addEventListener('click',saveClass);
  $('manageClass').addEventListener('change',e=>{ci=Number(e.target.value);renderManage()});
  $('addClassBtn').addEventListener('click',()=>{classes.push({id:uid(),name:'New Class',pupils:[],tools:builtIns()});ci=classes.length-1;store('sb9_classes',classes);renderManage()});
  $('portalClass').addEventListener('change',e=>{ci=Number(e.target.value);openPortal()});
  $('portalDay').addEventListener('change',renderPortal);
  $('exportBtn').addEventListener('click',exportOptions);
  $('downloadBtn').addEventListener('click',download);
  $('resetBtn').addEventListener('click',()=>{if(!tool)return;if(confirm('Reset today?')){records=records.filter(r=>!(r.classId===cls().id&&r.toolId===tool.id&&day(new Date(r.date))===day()));store('sb9_records',records);openTool(tool.id)}});
  document.querySelectorAll('.close').forEach(b=>b.addEventListener('click',()=>b.closest('.modal').classList.add('hidden')));
  if(sessionStorage.sb9)renderClasses();
}
window.addEventListener('error',event=>{const box=$('appError');if(box){box.textContent='Stat Buddy error: '+event.message;box.classList.remove('hidden')}console.error(event.error||event.message)});
try{bindApp()}catch(error){console.error(error);const box=$('appError');if(box){box.textContent='Stat Buddy could not start: '+error.message;box.classList.remove('hidden')}}
